import { publicAssetUrl } from '../lib/asset-url';
import type { GalleryItem } from '../lib/gallery/types';

const artwork = (id: string) => ({
  src: publicAssetUrl(`gallery-images/${id}.webp`),
  thumbnail: publicAssetUrl(`gallery-images/${id}-thumb.webp`),
});

/**
 * Generated concept artwork, including photographic-looking studies.
 * These are not photographs of real places or people. Most source artworks
 * already imagine recursion; the gallery adds precisely repeating copies.
 * Nest regions follow the actual openings, normalized to the uncropped source.
 */
export const galleryItems: GalleryItem[] = [
  {
    id: 'photo-coffee',
    title: 'Coffee, again',
    description: 'A chipped cup holds the whole quiet morning, down to the last crumb.',
    ...artwork('photo-coffee'),
    category: 'Photographic',
    alt: 'Generated photographic study of a chipped coffee cup on a wooden table, with smaller cups, spoons and green linen repeating inside the coffee.',
    nest: { x: 0.208, y: 0.128, w: 0.56, h: 0.56 },
    shape: 'ellipse',
  },
  {
    id: 'photo-courtyard',
    title: 'After the rain',
    description: 'A Berlin courtyard opens into another courtyard in a puddle between the stones.',
    ...artwork('photo-courtyard'),
    category: 'Photographic',
    alt: 'Generated photographic study of an empty yellow-walled Berlin courtyard with a bicycle and plant pot; the scene repeats inside a rain puddle.',
    nest: { x: 0.205, y: 0.377, w: 0.588, h: 0.588 },
    shape: 'ellipse',
  },
  {
    id: 'photo-camera',
    title: 'The camera sees itself',
    description: 'An old camera looks through its own lens. Its red strap follows it all the way in.',
    ...artwork('photo-camera'),
    category: 'Photographic',
    alt: 'Generated photographic study of a worn silver and black camera on a wooden table, with the same camera and red strap repeating inside its lens.',
    nest: { x: 0.338, y: 0.299, w: 0.38, h: 0.38 },
    shape: 'ellipse',
  },
  {
    id: 'photo-coast',
    title: 'The coast continues',
    description: 'Beyond the limestone arch: the same tide, the same shore, the same orange buoy.',
    ...artwork('photo-coast'),
    category: 'Photographic',
    alt: 'Generated photographic study of a limestone sea arch over a pebble beach, with the same arch and an orange buoy repeating along the coast.',
    nest: { x: 0.435, y: 0.355, w: 0.325, h: 0.325 },
    shape: 'ellipse',
  },
  {
    id: 'photo-greenhouse',
    title: 'A garden within',
    description: 'Each open greenhouse door leads back to the garden you just left.',
    ...artwork('photo-greenhouse'),
    category: 'Photographic',
    alt: 'Generated photographic study of a weathered glass greenhouse with tomato plants, a terracotta pot and a yellow watering can repeating through its doorway.',
    nest: { x: 0.38, y: 0.278, w: 0.307, h: 0.482 },
    shape: 'rect',
  },
  {
    id: 'lighthouse',
    title: 'The lighthouse within',
    description: 'A lighthouse keeps its own island glowing inside its great round lens.',
    ...artwork('lighthouse'),
    category: 'Imagined',
    alt: 'Generated artwork of a white lighthouse with a red roof on a rocky island, repeating inside a glowing brass-rimmed circular opening.',
    nest: { x: 0.358, y: 0.274, w: 0.285, h: 0.285 },
    shape: 'ellipse',
  },
  {
    id: 'moon-railway',
    title: 'The midnight railway',
    description: 'A red night train curves into a moon that holds a smaller moon.',
    ...artwork('moon-railway'),
    category: 'Imagined',
    alt: 'Generated artwork of a red passenger train on a curving stone railway through a hollow moon, with smaller moons and trains repeating in a starry sky.',
    nest: { x: 0.319, y: 0.15, w: 0.48, h: 0.48 },
    shape: 'ellipse',
  },
  {
    id: 'book-library',
    title: 'A book of books',
    description: 'Turn a page into a staircase. Follow it into the whole library again.',
    ...artwork('book-library'),
    category: 'Imagined',
    alt: 'Generated artwork of an open red book whose curved pages become library shelves and staircases, with the entire book repeating in a central frame.',
    nest: { x: 0.328, y: 0.298, w: 0.337, h: 0.408 },
    shape: 'rect',
  },
  {
    id: 'raindrop-aquarium',
    title: 'An ocean in a drop',
    description: 'Fish, coral and a shell. Inside the shell, another drop holds them all.',
    ...artwork('raindrop-aquarium'),
    category: 'Imagined',
    alt: 'Generated artwork of a luminous water drop containing red fish, coral and an ivory shell, with the complete aquarium repeating inside the shell.',
    nest: { x: 0.429, y: 0.539, w: 0.242, h: 0.242 },
    shape: 'ellipse',
  },
  {
    id: 'mountain-waterfall',
    title: 'Where the water returns',
    description: 'A snowy mountain pours its waterfall into a smaller version of the same valley.',
    ...artwork('mountain-waterfall'),
    category: 'Imagined',
    alt: 'Generated artwork of a snowy triangular mountain with forests and a waterfall, repeating through a huge circular arch in the mountain.',
    nest: { x: 0.288, y: 0.45, w: 0.423, h: 0.423 },
    shape: 'ellipse',
  },
  {
    id: 'recursive-theatre',
    title: 'Tonight: the theatre',
    description: 'An empty theatre raises its curtain on the entire theatre, waiting inside.',
    ...artwork('recursive-theatre'),
    category: 'Imagined',
    alt: 'Generated artwork of a miniature cutaway brick theatre with velvet curtains and empty seats, containing smaller copies of the entire theatre on its stage.',
    nest: { x: 0.327, y: 0.346, w: 0.346, h: 0.38 },
    shape: 'rect',
  },
  {
    id: 'clock-garden',
    title: 'Growing time',
    description: 'Flowers and little brass gears grow together in a pocket watch, around another watch.',
    ...artwork('clock-garden'),
    category: 'Imagined',
    alt: 'Generated artwork of a silver pocket watch filled with a flowering garden and mechanical plants, repeating inside a glass conservatory.',
    nest: { x: 0.41, y: 0.5, w: 0.18, h: 0.18 },
    shape: 'ellipse',
  },
  {
    id: 'paper-boat-city',
    title: 'A harbour for itself',
    description: 'A paper boat carries a whole coastal city, and a harbour for the boat that carries it.',
    ...artwork('paper-boat-city'),
    category: 'Imagined',
    alt: 'Generated artwork of a folded white paper boat carrying a coastal city and blue lighthouse, with smaller boat cities repeating through its harbour arch.',
    nest: { x: 0.339, y: 0.309, w: 0.335, h: 0.335 },
    shape: 'ellipse',
  },
  {
    id: 'pear-observatory',
    title: 'The pear observatory',
    description: 'A telescope, a winding stair and a brass doorway into the dark.',
    ...artwork('pear-observatory'),
    category: 'Early studies',
    alt: 'Generated artwork of a miniature observatory inside a golden pear, with a telescope, red staircase, blue roof and empty circular brass doorway.',
    nest: { x: 0.335, y: 0.394, w: 0.379, h: 0.379 },
    shape: 'ellipse',
  },
  {
    id: 'pear-observatory-generated-droste',
    title: 'The pear, inside the pear',
    description: 'The first imagined observatory opens its brass doorway onto its own little world.',
    ...artwork('pear-observatory-generated-droste'),
    category: 'Early studies',
    alt: 'Generated artwork of the pear observatory with smaller golden pear worlds already repeating inside its central brass doorway.',
    nest: { x: 0.335, y: 0.394, w: 0.379, h: 0.379 },
    shape: 'ellipse',
  },
  {
    id: 'berlin-summer-park',
    title: 'A summer circle',
    description: 'Four friends, a painted wooden hoop and an afternoon under the trees.',
    ...artwork('berlin-summer-park'),
    category: 'Early studies',
    alt: 'Generated summer park scene with four fictional friends gathered around a small painted wooden hoop beneath leafy trees.',
    nest: { x: 0.435, y: 0.417, w: 0.173, h: 0.173 },
    shape: 'ellipse',
  },
];
